### PR TITLE
Enhancements to create file and fixed tests

### PR DESCRIPTION
**Pull request by claudio4j**
* run.go - Create the parent directory if missing. Had issues creating
  OLM file and the parent dir didn't exist
* configuration_test.go fixed, as there was a missing attribute
* Added a header "generated by" to the generated yaml files

the build operation updated vendors files and CRD.

### CODE REVIEW

**Comment by claudio4j** [comment]
@lgarciaaco can you review ?

**Review by lgarciaaco — APPROVED** [review]

**Comment by claudio4j** [comment]
@lgarciaaco can you merge it ? I have no power here :)

**Comment by EricWittmann** [comment]
image

**Comment by claudio4j** [comment]
Thanks Eric.

**Pull request merged**
